// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dinogrpc.proto

package dinogrpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Animal struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AnimalType           string   `protobuf:"bytes,2,opt,name=animal_type,json=animalType,proto3" json:"animal_type,omitempty"`
	Nickname             string   `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Zone                 int32    `protobuf:"varint,4,opt,name=zone,proto3" json:"zone,omitempty"`
	Age                  int32    `protobuf:"varint,5,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Animal) Reset()         { *m = Animal{} }
func (m *Animal) String() string { return proto.CompactTextString(m) }
func (*Animal) ProtoMessage()    {}
func (*Animal) Descriptor() ([]byte, []int) {
	return fileDescriptor_f18eada6eecd7c27, []int{0}
}

func (m *Animal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Animal.Unmarshal(m, b)
}
func (m *Animal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Animal.Marshal(b, m, deterministic)
}
func (m *Animal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Animal.Merge(m, src)
}
func (m *Animal) XXX_Size() int {
	return xxx_messageInfo_Animal.Size(m)
}
func (m *Animal) XXX_DiscardUnknown() {
	xxx_messageInfo_Animal.DiscardUnknown(m)
}

var xxx_messageInfo_Animal proto.InternalMessageInfo

func (m *Animal) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Animal) GetAnimalType() string {
	if m != nil {
		return m.AnimalType
	}
	return ""
}

func (m *Animal) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *Animal) GetZone() int32 {
	if m != nil {
		return m.Zone
	}
	return 0
}

func (m *Animal) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

type Request struct {
	Nickname             string   `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_f18eada6eecd7c27, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func init() {
	proto.RegisterType((*Animal)(nil), "dinogrpc.animal")
	proto.RegisterType((*Request)(nil), "dinogrpc.request")
}

func init() {
	proto.RegisterFile("dinogrpc.proto", fileDescriptor_f18eada6eecd7c27)
}

var fileDescriptor_f18eada6eecd7c27 = []byte{
	// 208 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0xc9, 0xcc, 0xcb,
	0x4f, 0x2f, 0x2a, 0x48, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0xf1, 0x95, 0xaa,
	0xb9, 0xd8, 0x12, 0xf3, 0x32, 0x73, 0x13, 0x73, 0x84, 0xf8, 0xb8, 0x98, 0x32, 0x53, 0x24, 0x18,
	0x15, 0x18, 0x35, 0x58, 0x83, 0x80, 0x2c, 0x21, 0x79, 0x2e, 0x6e, 0x88, 0x4c, 0x7c, 0x49, 0x65,
	0x41, 0xaa, 0x04, 0x13, 0x50, 0x82, 0x33, 0x88, 0x0b, 0x22, 0x14, 0x02, 0x14, 0x11, 0x92, 0xe2,
	0xe2, 0xc8, 0xcb, 0x4c, 0xce, 0xce, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x06, 0xcb, 0xc2, 0xf9, 0x42,
	0x42, 0x5c, 0x2c, 0x55, 0xf9, 0x79, 0xa9, 0x12, 0x2c, 0x60, 0xe3, 0xc0, 0x6c, 0x21, 0x01, 0x2e,
	0xe6, 0xc4, 0xf4, 0x54, 0x09, 0x56, 0xb0, 0x10, 0x88, 0xa9, 0xa4, 0xca, 0xc5, 0x5e, 0x94, 0x5a,
	0x58, 0x9a, 0x5a, 0x5c, 0x82, 0x62, 0x18, 0x23, 0xaa, 0x61, 0x46, 0xe5, 0x5c, 0xdc, 0x2e, 0x40,
	0xf7, 0x06, 0xa7, 0x16, 0x95, 0x65, 0x26, 0xa7, 0x0a, 0x19, 0x70, 0x71, 0xba, 0xa7, 0x96, 0x38,
	0x42, 0x5c, 0x2d, 0xa8, 0x07, 0xf7, 0x1a, 0xd4, 0x28, 0x29, 0x01, 0x84, 0x10, 0xd4, 0x6b, 0x66,
	0x5c, 0xbc, 0x20, 0x1d, 0x39, 0x39, 0x10, 0x4d, 0xc5, 0x44, 0xe9, 0x32, 0x60, 0x4c, 0x62, 0x03,
	0x87, 0x96, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xa1, 0x8a, 0x2e, 0x36, 0x3f, 0x01, 0x00, 0x00,
}
